services:
  auth:
    image: "safegergis/tome-auth"
    env_file:
      - ./.env
    build:
      context:
        ./tome-auth/.
    ports:
        - "8082:8082"
  content:
    image: "safegergis/tome-content"
    env_file:
      - ./.env
    build:
      context:
        ./tome-content/.
    ports:
      - "8080:8080"

